# -*- coding: utf-8 -*-
"""Thresher_nonsense.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eA4bxNATv71TFPnrRYBMqET4p2cgR6XF
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt

filename = 'HUM_cleaned.csv'
# Update the file path to load from the /content/ directory
filepath = f'/content/{filename}'

# Load data
df = pd.read_csv(filepath)

# Drop rows with missing values in SECT MAX or SECT ENRL
df = df.dropna(subset=['SECT.MAX', 'SECT.ENRL'])

# Group by TERM and compute averages
grouped = df.groupby('TERM', as_index=False).agg({
    'SECT.MAX': 'mean',
    'SECT.ENRL': 'mean'
})

# Compute the average excess capacity
grouped['avg excess capacity'] = grouped['SECT.MAX'] - grouped['SECT.ENRL']

# Optional: rename columns for readability
grouped.rename(columns={
    'SECT.MAX': 'avg section max',
    'SECT.ENRL': 'avg section enrolled'
}, inplace=True)

# Plot the average excess capacity per term
plt.figure(figsize=(10, 5))
plt.plot(grouped['TERM'], grouped['avg excess capacity'], marker='o', color='green', label='Avg Excess Capacity')
plt.xlabel('Term')
plt.ylabel('Avg Excess Seats per Class')
plt.title(f'Average Excess Capacity per Section by Term: {filename.split(".")[0]}')
plt.xticks(rotation=45)
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

from google.colab import files

# Save to CSV
grouped.to_csv(f'{filename.split(".")[0]}avg_excess_capacity_by_term.csv', index=False)

# Trigger download
files.download(f'{filename.split(".")[0]}avg_excess_capacity_by_term.csv')



import pandas as pd

# Load the data
filename = 'HUM_cleaned.csv'

df = pd.read_csv(filename)
# Drop rows missing SECT ENRL
df = df.dropna(subset=['SECT.ENRL'])


# Extract year from TERM (e.g. "2021_2" → "2021")
df['YEAR'] = df['TERM'].astype(str)

# Group by year and sum SECT ENRL
yearly_totals = df.groupby('YEAR')['SECT.ENRL'].sum()

# Get values and compute the difference
enrl_2025 = yearly_totals.get('25_2', 0)
enrl_2021 = yearly_totals.get('21_2', 0)
difference = enrl_2025 - enrl_2021

# Print results
print(f'{filename.split(".")[0]}')
print(f"Total enrollment in Fall 2025: {enrl_2025}")
print(f"Total enrollment in Fall 2021: {enrl_2021}")
print(f"Difference (2025 - 2021): {difference}")

# Get the total number of rows
total_rows = df.shape[0]

# Print the result
print(f"Total number of classes: {total_rows}")

import pandas as pd

# Load the data
filename = 'EN_Cleaned.csv'

df = pd.read_csv(filename)
# Drop rows missing SECT ENRL
df = df.dropna(subset=['SECT.ENRL'])


# Extract year from TERM (e.g. "2021_2" → "2021")
df['YEAR'] = df['TERM'].astype(str)

# Group by year and sum SECT ENRL
yearly_totals = df.groupby('YEAR')['SECT.ENRL'].sum()

# Get values and compute the difference
enrl_2025 = yearly_totals.get('21_2', 0)
enrl_2021 = yearly_totals.get('25_2', 0)
difference = enrl_2025 - enrl_2021

# Print results
print(f'{filename.split(".")[0]}')
print(f"Total enrollment in Fall 2025: {enrl_2025}")
print(f"Total enrollment in Fall 2021: {enrl_2021}")
print(f"Difference (2025 - 2021): {difference}")

import pandas as pd

# Load the data
filename = 'Business_cleanedfinal.csv'

df = pd.read_csv(filename)
# Drop rows missing SECT ENRL
df = df.dropna(subset=['SECT ENRL'])


# Extract year from TERM (e.g. "2021_2" → "2021")
df['YEAR'] = df['TERM'].astype(str)

# Group by year and sum SECT ENRL
yearly_totals = df.groupby('YEAR')['SECT ENRL'].sum()

# Get values and compute the difference
enrl_2025 = yearly_totals.get('2025_2', 0)
enrl_2021 = yearly_totals.get('2021_2', 0)
difference = enrl_2025 - enrl_2021

# Print results
print(f'{filename.split(".")[0]}')
print(f"Total enrollment in Fall 2025: {enrl_2025}")
print(f"Total enrollment in Fall 2021: {enrl_2021}")
print(f"Difference (2025 - 2021): {difference}")

# Get the total number of rows
total_rows = df.shape[0]

# Print the result
print(f"Total number of classes: {total_rows}")

from google.colab import files
uploaded = files.upload()

#engineering graph
import pandas as pd
import matplotlib.pyplot as plt

filename = 'EN_COMBINED.csv'
# Update the file path to load from the /content/ directory
filepath = f'/content/{filename}'

# Load data
df = pd.read_csv(filepath)

# Drop rows with missing values in SECT MAX or SECT ENRL
df = df.dropna(subset=['SECT MAX', 'SECT ENRL'])

# Group by TERM and compute averages
grouped = df.groupby('TERM', as_index=False).agg({
    'SECT MAX': 'mean',
    'SECT ENRL': 'mean'
})

# Compute the average excess capacity
grouped['avg excess capacity'] = grouped['SECT MAX'] - grouped['SECT ENRL']

# Optional: rename columns for readability
grouped.rename(columns={
    'SECT MAX': 'avg section max',
    'SECT ENRL': 'avg section enrolled'
}, inplace=True)

# Plot the average excess capacity per term
plt.figure(figsize=(10, 5))
plt.plot(grouped['TERM'], grouped['avg excess capacity'], marker='o', color='green', label='Avg Excess Capacity')
plt.xlabel('Term')
plt.ylabel('Avg Excess Seats per Class')
plt.title(f'Average Excess Capacity per Section by Term: {filename.split(".")[0]}')
plt.xticks(rotation=45)
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

from google.colab import files

# Save to CSV
grouped.to_csv(f'{filename.split(".")[0]}avg_excess_capacity_by_term.csv', index=False)

# Trigger download
files.download(f'{filename.split(".")[0]}avg_excess_capacity_by_term.csv')

import pandas as pd

# Load the data
filename = 'Natural Sciences.csv'

df = pd.read_csv(filename)
# Drop rows missing SECT ENRL
df = df.dropna(subset=['SECT ENRL'])


# Extract year from TERM (e.g. "2021_2" → "2021")
df['YEAR'] = df['TERM'].astype(str)

# Group by year and sum SECT ENRL
yearly_totals = df.groupby('YEAR')['SECT ENRL'].sum()

# Get values and compute the difference
enrl_2025 = yearly_totals.get('2025_2', 0)
enrl_2021 = yearly_totals.get('2021_2', 0)
difference = enrl_2025 - enrl_2021

# Print results
print(f'{filename.split(".")[0]}')
print(f"Total enrollment in Fall 2025: {enrl_2025}")
print(f"Total enrollment in Fall 2021: {enrl_2021}")
print(f"Difference (2025 - 2021): {difference}")

# Get the total number of rows
total_rows = df.shape[0]

# Print the result
print(f"Total number of classes: {total_rows}")

import pandas as pd

# Load the data
filename = 'Social Sciences _Cleaned.csv'

df = pd.read_csv(filename)
# Drop rows missing SECT ENRL
df = df.dropna(subset=['SECT ENRL'])


# Extract year from TERM (e.g. "2021_2" → "2021")
df['YEAR'] = df['TERM'].astype(str)

# Group by year and sum SECT ENRL
yearly_totals = df.groupby('YEAR')['SECT ENRL'].sum()

# Get values and compute the difference
enrl_2025 = yearly_totals.get('2025_2', 0)
enrl_2021 = yearly_totals.get('2021_2', 0)
difference = enrl_2025 - enrl_2021

# Print results
print(f'{filename.split(".")[0]}')
print(f"Total enrollment in Fall 2025: {enrl_2025}")
print(f"Total enrollment in Fall 2021: {enrl_2021}")
print(f"Difference (2025 - 2021): {difference}")

# Get the total number of rows
total_rows = df.shape[0]

# Print the result
print(f"Total number of classes: {total_rows}")

#ENGI GRAPH
import pandas as pd
import matplotlib.pyplot as plt

filename = 'FINAL_EN_Cleaned.xlsx - Sheet1.csv'
# Update the file path to load from the /content/ directory
filepath = f'/content/{filename}'

# Load data
df = pd.read_csv(filepath)

# Drop rows with missing values in SECT MAX or SECT ENRL
df = df.dropna(subset=['SECT MAX', 'SECT ENRL'])

# Group by TERM and compute averages
grouped = df.groupby('TERM', as_index=False).agg({
    'SECT MAX': 'mean',
    'SECT ENRL': 'mean'
})

# Compute the average excess capacity
grouped['avg excess capacity'] = grouped['SECT MAX'] - grouped['SECT ENRL']

# Optional: rename columns for readability
grouped.rename(columns={
    'SECT MAX': 'avg section max',
    'SECT ENRL': 'avg section enrolled'
}, inplace=True)

# Plot the average excess capacity per term
plt.figure(figsize=(10, 5))
plt.plot(grouped['TERM'], grouped['avg excess capacity'], marker='o', color='green', label='Avg Excess Capacity')
plt.xlabel('Term')
plt.ylabel('Avg Excess Seats per Class')
plt.title(f'Average Excess Capacity per Section by Term: {filename.split(".")[0]}')
plt.xticks(rotation=45)
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

from google.colab import files

# Save to CSV
grouped.to_csv(f'{filename.split(".")[0]}avg_excess_capacity_by_term.csv', index=False)

# Trigger download
files.download(f'{filename.split(".")[0]}avg_excess_capacity_by_term.csv')

import pandas as pd

# Load the data
filename = 'FINAL_EN_Cleaned.xlsx - Sheet1.csv'

df = pd.read_csv(filename)
# Drop rows missing SECT ENRL
df = df.dropna(subset=['SECT ENRL'])


# Extract year from TERM (e.g. "2021_2" → "2021")
df['YEAR'] = df['TERM'].astype(str)

# Group by year and sum SECT ENRL
yearly_totals = df.groupby('YEAR')['SECT ENRL'].sum()

# Get values and compute the difference
enrl_2025 = yearly_totals.get('2025_2', 0)
enrl_2021 = yearly_totals.get('2021_2', 0)
difference = enrl_2025 - enrl_2021

# Print results
print(f'{filename.split(".")[0]}')
print(f"Total enrollment in Fall 2025: {enrl_2025}")
print(f"Total enrollment in Fall 2021: {enrl_2021}")
print(f"Difference (2025 - 2021): {difference}")

# Get the total number of rows
total_rows = df.shape[0]

# Print the result
print(f"Total number of classes: {total_rows}")